
title: "Nathanael Jones"
subtitle: "Ramblings of a computer linguist"

author:
   name: Nathanael Jones
   uri: http://nathanaeljones.com
   email: n@imazen.io
   google_profile: "http://google.com/profiles/104429865496810073908"


# If you want to use the Disqus service (http://disqus.com) to display
# comments on your site, register a Disqus account and then specify your
# site's short name here. A comment form will automatically be added to
# the bottom of your pages.
disqus_short_name: ndj7


content: content

# google_analytics_code
#     Set this if you want Google Analytics to track traffic on your site.
#     Probably best not to set a default value, but to set it in production.
#google_analytics_code: "UA-5218175-1"
production: 
  google_analytics_code: "UA-5218175-1"

# Google Webmaster and Analytics usually require a 'google[code].html' file be placed on the domain
# Use this feature to do this without polluting your directory structure
google_verify: [344a8f78fa8143f6, b4f699bd08907a51]
