
title: "Lilith River"
subtitle: "(formerly known as Nathanael Jones)"
url: http://nathanaeljones.com
atom_id: http://nathanaeljones.com

author:
   name: Lilith River
   uri: http://nathanaeljones.com
   email: lilith@imazen.io
   google_profile: "https://plus.google.com/u/0/104012989699866208923"
   linkedin_profile: "http://www.linkedin.com/in/nathanaeljones"
   twitter_profile: "https://twitter.com/lilith_river"
   github_profile: "https://github.com/lilith"


# If you want to use the Disqus service (http://disqus.com) to display
# comments on your site, register a Disqus account and then specify your
# site's short name here. A comment form will automatically be added to
# the bottom of your pages.
disqus_short_name: ndj7


# google_analytics_code
#     Set this if you want Google Analytics to track traffic on your site.
#     Probably best not to set a default value, but to set it in production.
#google_analytics_code: "UA-5218175-1"
production: 
  google_analytics_code: "UA-5218175-1"
  google_analytics_domain: "nathanaeljones.com" #Override domain for multiple subdomain support

# Google Webmaster and Analytics usually require a 'google[code].html' file be placed on the domain
# Use this feature to do this without polluting your directory structure
google_verify: [344a8f78fa8143f6, b4f699bd08907a51]
google_custom_search: "005556834036073640702:ds3gmqyjham"

less: 
  compress: true